<?php

$appUrl = rtrim((string) env('APP_URL', ''), '/');

return [
    'enabled' => env('HAPP_ROUTING_ENABLED', true),

    'name' => env('HAPP_ROUTING_NAME', 'AVA · RU DIRECT'),

    // Локальные копии — GitHub с VPS часто отдаёт 504/403, Happ не может скачать геофайлы.
    'geoip_url' => env('HAPP_GEOIP_URL', $appUrl.'/geo/geoip.dat'),
    'geosite_url' => env('HAPP_GEOSITE_URL', $appUrl.'/geo/geosite.dat'),

    'direct_sites' => [
        'geosite:ru',
        'geosite:category-gov-ru',
        'geosite:yandex',
        'geosite:mailru',
        'geosite:vk',
        'domain:tbank.ru',
        'domain:tinkoff.ru',
        'domain:tcsbank.ru',
        'domain:sberbank.ru',
        'domain:sber.ru',
        'domain:sberbank.com',
        'domain:online.sberbank.ru',
        'domain:vtb.ru',
        'domain:alfabank.ru',
        'domain:alfabank.com',
        'domain:open.ru',
        'domain:psbank.ru',
        'domain:rshb.ru',
        'domain:gazprombank.ru',
        'domain:raiffeisen.ru',
        'domain:rosbank.ru',
        'domain:sovcombank.ru',
        'domain:mkb.ru',
        'domain:uralsib.ru',
        'domain:akbars.ru',
        'domain:pochtabank.ru',
        'domain:cbr.ru',
        'domain:nspk.ru',
        'domain:sbp.nspk.ru',
        'domain:mironline.ru',
        'domain:gosuslugi.ru',
        'domain:nalog.gov.ru',
        'domain:nalog.ru',
        'domain:mos.ru',
        'domain:pfr.gov.ru',
        'domain:sfr.gov.ru',
        'domain:fssp.gov.ru',
        'domain:roskazna.gov.ru',
        'domain:mvd.ru',
        'domain:gibdd.ru',
        'domain:ozon.ru',
        'domain:wildberries.ru',
        'domain:wb.ru',
        'domain:aliexpress.ru',
        'domain:market.yandex.ru',
        'domain:megamarket.ru',
        'domain:lamoda.ru',
        'domain:dns-shop.ru',
        'domain:mvideo.ru',
        'domain:eldorado.ru',
        'domain:citilink.ru',
        'domain:avito.ru',
        'domain:cian.ru',
        'domain:youla.ru',
        'domain:auto.ru',
        'domain:drom.ru',
        'domain:delivery-club.ru',
        'domain:samokat.ru',
        'domain:perekrestok.ru',
        'domain:vkusvill.ru',
        'domain:lenta.com',
        'domain:magnit.ru',
        'domain:kinopoisk.ru',
        'domain:ivi.ru',
        'domain:wink.ru',
        'domain:okko.tv',
        'domain:more.tv',
        'domain:start.ru',
        'domain:premier.one',
        'domain:rutube.ru',
        'domain:zvuk.com',
        'domain:music.yandex.ru',
        'domain:beeline.ru',
        'domain:megafon.ru',
        'domain:mts.ru',
        'domain:tele2.ru',
        'domain:rt.ru',
        'domain:rostelecom.ru',
        'domain:dom.ru',
        'domain:2gis.ru',
        'domain:2gis.com',
        'domain:dzen.ru',
        'domain:lan',
        'domain:local',
        'domain:home',
        'domain:internal',
    ],

    'direct_ip' => [
        'geoip:ru',
        '10.0.0.0/8',
        '172.16.0.0/12',
        '192.168.0.0/16',
        '127.0.0.0/8',
        '169.254.0.0/16',
        '100.64.0.0/10',
        '224.0.0.0/4',
        '240.0.0.0/4',
        '255.255.255.255/32',
    ],

    'proxy_sites' => [],
    'proxy_ip' => [],
];
